services:
  devcanvas:
    build: ./docker/dev/
    volumes:
      - devcanvas:/var/www/devcanvas
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - traefik
    links:
      - mysql
    labels:
      - "traefik.enable=true"
      - ${PROJECT_TRAEFIK_LABELS_HOST}

  mysql:
    image: mysql
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${PROJECT_NAME}
      MYSQL_ROOT_PASSWORD: ${PROJECT_MYSQL_PASSWORD}
      MYSQL_PASSWORD: ${PROJECT_MYSQL_PASSWORD}
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "--host=localhost",
          "--user=root",
          "--password=${PROJECT_MYSQL_PASSWORD}",
        ]
      retries: 5
      interval: 30s
      timeout: 10s

  traefik:
    image: traefik:v3.2
    command:
      - "--api.insecure=true"
      - "--providers.docker"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  mysql:
  devcanvas:
